on: [push, pull_request]
name: Android
jobs:
  Integration:
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/checkout@v2
    - name: Setup environment
      run: |
        git clone https://github.com/kivy/buildozer
        cd buildozer
        python setup.py build
        pip install -e .
        pip install Cython
        cd
        ls
    - run: buildozer --help
    - run: buildozer init
    - name: SDK, NDK and p4a download
      run: |
        sed -i.bak "s/# android.accept_sdk_license = False/android.accept_sdk_license = True/" buildozer.spec
        sed -i.bak "s/#p4a.branch = master/p4a.branch = develop/" buildozer.spec
        sed -i.bak "s/title = My Application/title = pppdos/" buildozer.spec
        sed -i.bak "s/package.name = myapp/package.name = pppdos/" buildozer.spec
        sed -i.bak "s/requirements = python3,kivy/requirements = python3,kivy,scapy/" buildozer.spec
        sed -i.bak "s/#android.permissions = INTERNET/android.permissions = INTERNET/" buildozer.spec
        sed -i.bak "s/android.arch = armeabi-v7a/android.arch = arm64-v8a/" buildozer.spec
        sed -i.bak "s/#p4a.branch = master/p4a.branch = develop/" buildozer.spec
        buildozer android p4a -- --help
    # Install OS specific dependencies
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt -y install automake
    - name: Install macOS dependencies
      if: matrix.os == 'macOS-latest'
      run: |
        brew install automake
        sudo ln -sfn /usr/local/opt/openssl /usr/local/ssl
    - name: buildozer android debug
      env:
        SRC: ${{ secrets.SRC }}
        DST: ${{ secrets.DST }}
      run: |
        buildozer android_new debug deploy run
        
    - uses: actions/upload-artifact@v2
      with:
        name: update_apk
        path: bin/*
